services:
  - type: web
    name: smart-movie-agent
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OMDB_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
